force-app/main/default/objects/Session_Speaker__c/Session_Speaker__c.object-meta.xml
<CustomObject>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SESP-{00000}</displayFormat>
        <label>Session Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Speaker__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Speakers</relationshipLabel>
    <relationshipName>Session_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Session_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Speaker Nuber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestRejectDoubleBooking.cls
@isTest
public class TestRejectDoubleBooking {
    
    
    static testmethod void TestSingleBooking(){
        Datetime now  = System.now();
        Speaker__c spe = new Speaker__c(First_Name__c = 'Murali', Last_Name__c = 'Karri');
        Insert spe;
        
        Session__c ss = new Session__c(Name = 'Python', Session_Date__c = now);
        insert ss;
        
        Session_Speaker__c ssp = new Session_Speaker__c(Speaker__c = spe.Id, Session__c = ss.Id);
        
        Test.StartTest();
        Database.SaveResult result = Database.insert(ssp,false);
        Test.stopTest();
        
        
        System.assert(result.isSuccess());
    }
    
    static testmethod void TestDoubleBooking(){
        
        Datetime now = System.now();
        
        Speaker__c spe = new Speaker__c(First_Name__c = 'Ajay', Last_Name__c = 'Kolli');
        insert spe;
        
        Session__c ses1 = new Session__c(Name = 'React JS', Session_Date__c	= now);
        insert ses1;
        
        Session__c ses2 = new Session__c(Name = 'NODE JS', Session_Date__c	= now);
        insert ses2;
        
        Session_Speaker__c ssp1 = new Session_Speaker__c(Session__c = ses1.Id,Speaker__c = spe.Id);
        insert ssp1;
        
        Session_Speaker__c ssp2 = new Session_Speaker__c(Session__c = ses2.Id,Speaker__c = spe.Id);
        
        Test.StartTest();
        Database.SaveResult result = Database.insert(ssp2,false);
        Test.stopTest();
        
        System.assert(!result.isSuccess());
    }

}