force-app/main/default/objects/Approval__c/Approval__c.object-meta.xml
<CustomObject>
    <label>Approval</label>
    <nameField>
        <label>Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <referenceTo>Condition__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <label>Condition</label>
    <nameField>
        <label>Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConditionProcess.cls
public with sharing class ConditionProcess {
    
   	public Boolean showButton{get;set;}
    //public Boolean showButton2{get;set;}
    
    public Condition__c a{get;set;}
    public ConditionProcess(){
        a = new Condition__c();
        a = [select status__c, Total_Amount__c, Name from Condition__c where Id = : ApexPages.currentPage().getParameters().get('Id')];
        
        if(a.status__c == 'Draft'){
            showButton = true;
            //showButton2 = false;	
        }

        
    }
    
    public void approvemethod(){
        if(a.status__c  ==  'Draft'){
            
            //showButton2 = true;
            a.status__c = 'Pending Approval';
            update a;
        }
        
		List<Approval__c> newob = new List<Approval__c>();
        
            if(a.Total_Amount__c < 10000){
                Approval__c acc2 = new Approval__c();
                acc2.Condition__c = a.Id;
                acc2.Name = a.Name + ' request';
                acc2.Total__c = a.Total_Amount__c;
                newob.add(acc2);
            }
            else if(a.Total_Amount__c >= 10000){
                
                Approval__c acc1 = new Approval__c();

                acc1.Condition__c = a.Id;
                acc1.Name = a.Name + ' Approval Request 1';
                acc1.Total__c = a.Total_Amount__c;
                newob.add(acc1);
                Approval__c acc3 = new Approval__c();
                acc3.Condition__c = a.Id;
                acc3.Name = a.Name + ' Approval Request 2';
                acc3.Total__c = a.Total_Amount__c;
                
                newob.add(acc3);   
            }

             insert newob;
        
        showButton = false;
        
    }
    /*
    public void closeMethod(){
        if(a.status__c == 'Approved'){
			//showButton2 = false;
            a.status__c = 'Closed';
            update a;
        }

    }
*/

}