force-app/main/default/objects/Approval__c/Approval__c.object-meta.xml
<CustomObject>
    <label>Approval</label>
    <nameField>
        <label>Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <referenceTo>Condition__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <label>Condition</label>
    <nameField>
        <label>Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalTriggerHandler.cls
public class ApprovalTriggerHandler {
    public static void ApproveConditon(){
         
        ApprovalTriggerDMl.ApprovalProcess(Trigger.New);

        /*
        List<Condition__c> alter = new List<Condition__c>();
           Approval__c con = new Approval__c();
            for(Approval__c act : list1){
                con = [Select Condition__r.Id, Condition__r.Total_Amount__c, Condition__r.status__c from Approval__c where id = :act.Id];
                Condition__c ida = new Condition__c();
                ida = [select Id,Total_Amount__c,status__c from Condition__c where id=:con.Condition__c];
                if(act.Total__c < 10000){
                    if(act.Status__c == 'Approved'){
                        
                        ida.status__c = 'Approved';
                         alter.add(ida);
                    }
                    if(act.status__c == 'Rejected'){
                        
                        ida.status__c = 'Rejected';
                        alter.add(ida);
                        
                    }
                }
                
                else if(act.Total__c >= 10000){
                    List<Approval__c> val = [select Id,Status__c from Approval__c where Condition__c = :con.Condition__c];
                    for(Integer i=0;i<val.size();i++){
                        if(val[0].Status__c == 'Approved' && val[1].Status__c == 'Approved'){
                        ida.status__c = 'Approved';
                        alter.add(ida);
                        
                    }
                    if(val[0].Status__c == 'Rejected' && val[1].Status__c == 'Rejected'){
                        ida.status__c = 'Rejected';
                        alter.add(ida);
                        
                    }
                        if(val[0].Status__c == 'Rejected' && val[1].Status__c == 'Approved'){
                        ida.status__c = 'Rejected';
                        alter.add(ida);
                        }
                        if(val[0].Status__c == 'Approved' && val[1].Status__c == 'Rejected'){
                        ida.status__c = 'Rejected';
                        alter.add(ida);
                        }
                        break;
                    }
                    
                    
                        
                    }

                        
}
        
            update alter;
*/
    }
}